stages:
  - test
cache:
  paths:
    - node_modules/

tests:
  stage: test
  image: mcr.microsoft.com/playwright:focal
  script:
    - export TESTOMATIO="${testomatio}"
    - export TESTOMATIO_URL="${testomatio_url}"
    - export TESTOMATIO_RUN="${run}"
    - cd codeceptJS
    - npm i
    - npx codeceptjs run-workers 2 --grep "${grep}"
    - echo "Finished!"
